### ISSUE TITLE
Training of the Logistic Regression Models

### ISSUE THREAD

**Issue by oriolfornes** [smlmbrt/SimilarityRegression#1]
For the 2020 release of JASPAR, we are implementing your recently described similarity regression approach.

We are following the methods as described in the manuscript, with the only differences being the use of Tomtom e-values as values for Y (instead of E-score overlaps) and Python’s scikit-learn (instead of R).

According to the manuscript, TF-pairs with E-score overlaps >=75% and <20% are regarded as positive and negative, respectively, and are used for computing precision and recall metrics and train the logistic regression models. Hence, for training the logistic regression models, do you remove/mask all TF pairs whose E-score overlaps are between 75 and 20%?

Thank you in advance.

**Comment by smlmbrt** [comment]
HI @oriolfornes, sounds cool!

Re: motif similarity - that should work. I might also recommend [MoSBAT](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5181567/) ([github](https://github.com/csglab/MoSBAT)) for that purpose, as it doesn't require motif alignment. I originally developed MoSBAT to use with similarity regression (it works), but ended up going with the PBM E-score overlaps for consistency

Re: training samples - all observations are used (besides holding a single TF's pairs for testing during cross-validation). The labels for training are: 

- Positives (>= 25th percentile of motif similarity (E-Score Overlap) from replicate experiments. This number changes between TF families) 
- Negatives (everything else)

For model evaluation the labels are:
- Highly Similar (same as above)
- Ambiguous (inbetween the 2 thresholds)
- Dissimilar (< 20% E-score overlap, but this will vary depending on your use case)

Hope that explains everything.

**Comment by smlmbrt** [comment]
RE: scikit-learn - make sure you find/use a model that can constrain the coefficients to be positive. This didn't seem to be available when I implemented SR which is why I used glmnet.
